---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04-amd64

suites:
  - name: default
    run_list:
      - 'recipe[rails_multi_vm::default]'
    attributes:
  - name: database
    run_list:
      - 'recipe[rails_multi_vm::database]'
    attributes:
      postgresql:
        password:
          postgres: '5d30a314a0f9dce30170db5ba25fd195'
      pg:
        compile_time: 'false'