---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04-amd64

suites:
  - name: default
    run_list:
      - 'recipe[rails_multi_vm::default]'
    attributes:
  - name: database
    run_list:
      - 'recipe[rails_multi_vm::database]'
    attributes:
      app:
        database:
          user: 'test'
          password: 'test'
      postgresql:
        pg_hba:
          - type:   'host'
            db:     'all'
            user:   'postgres'
            addr:   '127.0.0.1/32'
            method: 'md5'
          - type:   'host'
            db:     'all'
            user:   'test'
            addr:   '127.0.0.1/32'
            method: 'md5'
        password:
          postgres: '5d30a314a0f9dce30170db5ba25fd195'
        config:
          listen_addresses: '0.0.0.0'
  - name: app
    run_list:
      - 'recipe[ruby_build]'
      - 'recipe[rails_multi_vm::app]'
    attributes:
      rbenv:
        global: '2.2.1'
        rubies:
          - '2.2.1'
        gems:
          2.2.1:
            - name: 'bundler'
      ruby_build:
        upgrade: true
