name             'rails_multi_vm'
maintainer       'Blake Tidwell'
maintainer_email 'YOUR_EMAIL'
license          'Apache 2.0'
description      'Installs/Configures rails_multi_vm'
long_description 'Installs/Configures rails_multi_vm'
version          '0.1.0'
