name             'rails_multi_vm'
maintainer       'Blake Tidwell'
maintainer_email 'YOUR_EMAIL'
license          'Apache 2 License'
description      'Installs/Configures rails_multi_vm'
long_description 'Installs/Configures rails_multi_vm'
version          '0.1.0'

depends          'apt', '~> 2.7.0'
depends          'database', '~> 4.0.0'
depends          'postgresql', '~> 3.4.0'
